---
- name: LAMP Setup
  hosts: all
  remote_user: root

  tasks:

  - name: Installing Packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - apache2
      - mysql-server
      - php 
      - libapache2-mod-php 
      - php-mysql
      - python3-pymysql

## Equivalent of running mysql_secure_installation
  - name: Set root password
    no_log: true
    mysql_user:
      name: root
      password: PLACE_YOUR_PASSWORD_HERE
      login_unix_socket: /var/run/mysqld/mysqld.sock
    
  - name: Create .my.cnf for easier mysql automation
    no_log: true
    blockinfile:
      path: ~/.my.cnf
      create: yes
      block: |
        [client]
        user=root
        password="PLACE_YOUR_PASSWORD_HERE"

  - name: Remove Anonymous mysql_user
    no_log: true
    community.mysql.mysql_user:
      name: ''
      state: absent

  - name: Removes test database
    no_log: true
    community.mysql.mysql_db:
      name: test
      state: absent

  - name: Disallow Remote Root login
    no_log: true
    community.mysql.mysql_query:
      login_db: mysql
      query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
      - FLUSH PRIVILEGES;

  - name: Configure apache2
    lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      regexp: "^	DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm$"
      line: "	DirectoryIndex index.php index.html index.cgi index.pl index.php index.xhtml index.htm"

  handlers:
  - name: Restart Apache2
    service:
      name: apache2
      state: restarted
