---
- name: LEMP Setup
  hosts: all
  remote_user: root

  tasks:

  - name: Installing Packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - mysql-server
      - php 
      - php-fpm
      - php-mysql
      - python3-pymysql

## Equivalent of running mysql_secure_installation
  - name: Set root password
    no_log: true
    mysql_user:
      name: root
      password: "PLACE_YOUR_PASSWORD_HERE"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    
  - name: Create .my.cnf for easier mysql automation
    no_log: true
    blockinfile:
      path: ~/.my.cnf
      create: yes
      block: |
        [client]
        user=root
        password="PLACE_YOUR_PASSWORD_HERE"

  - name: Remove Anonymous mysql_user
    no_log: true
    community.mysql.mysql_user:
      name: ''
      state: absent

  - name: Removes test database
    no_log: true
    community.mysql.mysql_db:
      name: test
      state: absent

  - name: Disallow Remote Root login
    no_log: true
    community.mysql.mysql_query:
      login_db: mysql
      query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
      - FLUSH PRIVILEGES;

  # - name: Configure Nginx


  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
